### ISSUE TITLE
Locked to version 1.4.2

### ISSUE THREAD

**Issue by dvins** [kaishuu0123/homebrew-erd-go#1]
Added this tap and installed from it, but the only version of `erd-go` it will pull is 1.4.2, even though 1.4.3 is now available.

**Comment by kaishuu0123** [comment]
@dvins 
Thanks for your issue.
I updated. please confirm.

```
$ brew update
$ brew reinstall erd-go
```

**Comment by dvins** [comment]
Thanks @kaishuu0123, this works and beats manually editing the brew. I have another question, but more appropriate inside the erd-go project so will leave it there.
